# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRK7zG7W1LBqRS0UoehQmhBZ_mlHbfMS
"""

# 台形の面積を計算する関数
def trapezoid(a,b,c,):
    return int((a+b)* c / 2)

# 台形の上底と下底と高さを設定
upper = 10
bottom = 20
height = 5

# 台形の面積を計算する関数を呼び出して計算
area = trapezoid(upper,bottom,height)
print("台形の面積は["+str(area)+"]㎠です")

# 　台形の上底と下底と高さを設定
upper = input("上底　：")
bottom = input("下底　：")
height = input("高さ　:")

#  台形関数の計算
area = (int(upper) + int(bottom)) * int(height) / 2
print(f"台形の面積は{area} ㎠です")

