# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xf_qpvnLjsxu15ANSAzLfuJa-541qQ7r
"""

# 変数varに正の整数を代入する
var = 25

# 3の倍数と５の倍数に両方に該当する場合は「FizzBuzz」を出力
if var % 15 == 0:
    print("FizzBuzz")

# 3の倍数の場合は「Fizz」を出力
elif var % 3 == 0:
    print("Fizz")

# ５の倍数の場合は「Buzz」を出力
elif var % 5 == 0:
    print("Buzz")

#どの場合にも該当しない場合は、変数varの値を出力
else:
    print(var)

